### ISSUE TITLE
WEB - Criar escopo do projeto em Vue

### ISSUE THREAD

**Issue by castilh0s** [restaurante-popular-catolicasc/web#4]

**Comment by castilh0s** [comment]
Teremos algum framework para componentes ou estilos? Qual? 
cc @restaurante-popular-catolicasc/lideres

**Comment by rafaelmatsumoto** [comment]
Penso que o Vuetify é uma opção interessante por prover o Material Design. Outra opção é o BootstrapVue pois se trata de uma tecnologia bastante conhecida pelos estudantes.

**Comment by castilh0s** [comment]
Então, eu tava pensando em usar o Vuetify mesmo, por conta dos componentes, o problema são montar os testes com ele, que é meio chatinho, mas nada muito trabalhoso

**Comment by murillo94** [comment]
Estou por vocês, aquele que escolherem eu aceito :) mas gostei do `BootstrapVue` e acho que vai ser mais izi da galera entender me parece.

**Comment by castilh0s** [comment]
Acabei optando pelo `Vuetify` por causa da documentação e maior quantidade de componentes
